<template>
  <section class="max-w-7xl mx-auto">
    <div>
      <h1 class="font-extrabold text-[#222328] text-[32px]">
        The Community Showcase
      </h1>
      <p class="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>

    <div class="mt-16">
      <FormField
        labelName="Search posts"
        type="text"
        name="text"
        placeholder="Search posts"
        :value="searchTerm"
        :handleChange="handleSearchChange"
      />
    </div>

    <div class="mt-10">
      <div v-if="loading" class="flex justify-center items-center">
        <AppLoader />
      </div>
      <template v-else>
        <h2 v-if="searchTerm" class="font-medium text-[#666e75] text-xl mb-3">
          Showing results for
          <span class="text-[#222328]">{{ searchTerm }}</span>
        </h2>

        <div
          class="grid lg:grid-col-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3"
        >
          <RenderCards
            v-if="searchTerm"
            :data="searchedResults"
            title="No search results found"
          />
          <RenderCards v-else :data="posts" title="No posts found" />
        </div>
      </template>
    </div>
  </section>
</template>

<script>
import AppCard from '../components/AppCard.vue';
import AppLoader from '../components/AppLoader.vue';
import FormField from '../components/FormField.vue';
import RenderCards from '../components/RenderCards.vue';

export default {
  name: 'HomeView',
  data() {
    return {
      loading: false,
      posts: [],
      searchTerm: '',
      searchedResults: [],
      searchTimeout: null,
    };
  },
  async mounted() {
    this.loading = true;
    try {
      const response = await fetch(
        'https://ai-image-generator-backend-hazel.vercel.app/api/v1/post',
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );
      if (response.ok) {
        const result = await response.json();
        this.posts = result.data.reverse();
      }
    } catch (e) {
      alert(e);
    } finally {
      this.loading = false;
    }
  },
  components: { AppLoader, AppCard, FormField, RenderCards },
  methods: {
    handleSearchChange(e) {
      clearTimeout(this.searchTimeout);
      this.searchTerm = e.target.value;
      this.searchTimeout = setTimeout(() => {
        const searchResult = this.posts.filter(
          (item) =>
            item.name.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
            item.prompt.toLowerCase().includes(this.searchTerm.toLowerCase())
        );
        this.searchedResults = searchResult;
        console.log(searchResult);
      }, 500);
    },
  },
};
</script>
